// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from '@tanstack/vue-query';

import { createTaskTasksPost, type Options } from '../sdk.gen';
import type { CreateTaskTasksPostData, CreateTaskTasksPostError, CreateTaskTasksPostResponse } from '../types.gen';

/**
 * Create Task
 */
export const createTaskTasksPostMutation = (options?: Partial<Options<CreateTaskTasksPostData>>): UseMutationOptions<CreateTaskTasksPostResponse, CreateTaskTasksPostError, Options<CreateTaskTasksPostData>> => {
    const mutationOptions: UseMutationOptions<CreateTaskTasksPostResponse, CreateTaskTasksPostError, Options<CreateTaskTasksPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createTaskTasksPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
