// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/vue-query';

import { client } from '../client.gen';
import { createTask, deleteAllCompletedTasks, deleteTask, getAllTasks, type Options, updateTask } from '../sdk.gen';
import type { CreateTaskData, CreateTaskError, CreateTaskResponse2, DeleteAllCompletedTasksData, DeleteAllCompletedTasksResponse, DeleteTaskData, DeleteTaskError, DeleteTaskResponse, GetAllTasksData, GetAllTasksResponse2, UpdateTaskData, UpdateTaskError, UpdateTaskResponse } from '../types.gen';

/**
 * Delete All Completed Tasks
 */
export const deleteAllCompletedTasksMutation = (options?: Partial<Options<DeleteAllCompletedTasksData>>): UseMutationOptions<DeleteAllCompletedTasksResponse, DefaultError, Options<DeleteAllCompletedTasksData>> => {
    const mutationOptions: UseMutationOptions<DeleteAllCompletedTasksResponse, DefaultError, Options<DeleteAllCompletedTasksData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteAllCompletedTasks({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getAllTasksQueryKey = (options?: Options<GetAllTasksData>) => createQueryKey('getAllTasks', options);

/**
 * Get All Tasks
 */
export const getAllTasksOptions = (options?: Options<GetAllTasksData>) => queryOptions<GetAllTasksResponse2, DefaultError, GetAllTasksResponse2, ReturnType<typeof getAllTasksQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllTasks({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllTasksQueryKey(options)
});

/**
 * Create Task
 */
export const createTaskMutation = (options?: Partial<Options<CreateTaskData>>): UseMutationOptions<CreateTaskResponse2, CreateTaskError, Options<CreateTaskData>> => {
    const mutationOptions: UseMutationOptions<CreateTaskResponse2, CreateTaskError, Options<CreateTaskData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createTask({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Task
 */
export const deleteTaskMutation = (options?: Partial<Options<DeleteTaskData>>): UseMutationOptions<DeleteTaskResponse, DeleteTaskError, Options<DeleteTaskData>> => {
    const mutationOptions: UseMutationOptions<DeleteTaskResponse, DeleteTaskError, Options<DeleteTaskData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteTask({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Task
 */
export const updateTaskMutation = (options?: Partial<Options<UpdateTaskData>>): UseMutationOptions<UpdateTaskResponse, UpdateTaskError, Options<UpdateTaskData>> => {
    const mutationOptions: UseMutationOptions<UpdateTaskResponse, UpdateTaskError, Options<UpdateTaskData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateTask({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
