// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};

/**
 * CreateTaskRequest
 */
export type CreateTaskRequest = {
    /**
     * Is Checked
     */
    is_checked: boolean;
    /**
     * Task
     */
    task: string;
};

/**
 * CreateTaskResponse
 */
export type CreateTaskResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Is Checked
     */
    is_checked: boolean;
    /**
     * Task
     */
    task: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type CreateTaskTasksPostData = {
    body: CreateTaskRequest;
    path?: never;
    query?: never;
    url: '/tasks/';
};

export type CreateTaskTasksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskTasksPostError = CreateTaskTasksPostErrors[keyof CreateTaskTasksPostErrors];

export type CreateTaskTasksPostResponses = {
    /**
     * Successful Response
     */
    200: CreateTaskResponse;
};

export type CreateTaskTasksPostResponse = CreateTaskTasksPostResponses[keyof CreateTaskTasksPostResponses];
